version: 0.2

phases:
  build:
    commands:
      - yarn run docker

artifacts:
  files:
    - build/**/*
    - yarn.lock
    - package.json
    - Dockerfile
  secondary-artifacts:
    BuildArtifact:
      files:
        - '**/*'
      name: BuildArtifact
    BuildArtif:
      files:
        - '**/*'
      name: BuildArtif